# Generated by Django 4.2.1 on 2023-07-08 16:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Examp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=111)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "main_examp",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Batafsil"),
                ),
                ("time", models.PositiveIntegerField(null=True, verbose_name="Vaqt")),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examp",
                        to="course.lessons",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon",
                "verbose_name_plural": "Imtihonlar",
            },
        ),
        migrations.CreateModel(
            name="FreeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ochiq Kategoriya",
                "verbose_name_plural": "Ochiq Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="FreeSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Batafsil"),
                ),
                (
                    "examp_type",
                    models.CharField(
                        choices=[
                            ("always", "Doimiy imtihonlar"),
                            ("dayly", "Kunlik imtihonlar"),
                            ("weekly", "Haftalik imtihonlar"),
                            ("monthly", "Oylik imtihonlar"),
                        ],
                        default="always",
                        max_length=20,
                        verbose_name="Imtihon turi",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_subcategories",
                        to="exam.freecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ochiq Kichik kategoriya",
                "verbose_name_plural": "Ochiq Kichik kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Batafsil"),
                ),
                (
                    "examp_type",
                    models.CharField(
                        choices=[
                            ("always", "Doimiy imtihonlar"),
                            ("dayly", "Kunlik imtihonlar"),
                            ("weekly", "Haftalik imtihonlar"),
                            ("monthly", "Oylik imtihonlar"),
                        ],
                        default="always",
                        max_length=20,
                        verbose_name="Imtihon turi",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="exam.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kichik kategoriya",
                "verbose_name_plural": "Kichik kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=exam.models.slug_funckion_for_result_model,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("ball", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("coin", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("answers", models.JSONField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "examp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exam.examp",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exam.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natija",
                "verbose_name_plural": "Natijalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=123)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=exam.models.slug_funckion_for_question_model,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "examp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.examp",
                    ),
                ),
                (
                    "free_subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.freesubcategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
            },
        ),
        migrations.CreateModel(
            name="FreeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=exam.models.slug_funckion_for_free_result_model,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("ball", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("answers", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_results",
                        to="exam.freesubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ochiq Natija",
                "verbose_name_plural": "Ochiq Natijalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(max_length=221, verbose_name="Answer Text"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=exam.models.slug_funckion_for_answer_model,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("true_answer", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
            },
        ),
    ]
