# Generated by Django 4.2.1 on 2023-07-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_coursecategory_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="teachers_photo/%Y/%m/%d/",
                verbose_name="Rasm",
            ),
        ),
    ]
