# Generated by Django 4.2.1 on 2023-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_category_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to="lessons_file/None_<built-in function id>"
            ),
        ),
    ]
